about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'new/',
        views.new_post,
        name='new_post'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group'
    ),
    path(
        '<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        '<str:username>/<int:post_id>/',
        views.post_view,
        name='post'
    ),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("thank-you/", views.thankyou, name="thank-you"),
    path("contact/", views.user_contact, name="contact")
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

'''
Импорт правил из приложений posts, admin, users
( Если правила в этом приложении не найдены, обращаемся к django.contrib...)
'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы',
                             null=False)
    slug = models.SlugField(verbose_name='Ссылка', unique=True,
                            help_text='Задайте ссылку на вашу группу')
    description = models.TextField(verbose_name='Описание группы',
                                   max_length=300)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор поста',
                               related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              verbose_name='Тег группы',
                              related_name='posts', blank=True, null=True,
                              help_text='Ключ для построения ссылки')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

users/models.py
from django.db import models

from .validators import validate_not_empty


'''
Визитка, с проверкой на заполненность некоторых полей
'''


class Contact(models.Model):
    name = models.CharField(verbose_name="Ваше имя", max_length=100,
                            validators=[validate_not_empty])
    email = models.EmailField(verbose_name="Ваша почта")
    subject = models.CharField(verbose_name="Тема письма", max_length=100)
    body = models.TextField(verbose_name="Текст письма",
                            validators=[validate_not_empty])
    is_answered = models.BooleanField(default=False)

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from .models import Contact


User = get_user_model()

'''
Форма регистрации
'''


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")


'''
Форма для связи
'''


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')

about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'author.html'


class AboutTechView(TemplateView):
    template_name = 'tech.html'

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from yatube.settings import POSTS
from .models import Group, Post, User
from .forms import PostForm


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'paginator': paginator,
        'page': page,
    }
    return render(request, 'index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'group': group,
        'paginator': paginator,
        'page': page,
    }
    return render(
        request, 'group.html', context
    )


@login_required
def new_post(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'new.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:index')


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'author': author,
        'paginator': paginator,
        'page': page,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, id=post_id, author=author)
    context = {
        'author': author,
        'post': post,
    }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    if not request.user.username == username:
        return redirect('posts:post', username, post_id)
    post = Post.objects.get(id=post_id, author=request.user)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post',
                        username=post.author.username, post_id=post.id)
    context = {
        'form': form,
        'post': post
    }
    return render(request, 'new.html', context)

users/views.py
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import ContactForm, CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("signup")
    template_name = "signup.html"


def send_msg(email, name, subject, body):
    sub = f"Письмо от {name} ({email})"
    bod = f""" Тема письма: {subject}
    Содержание:{body}
    """
    send_mail(
        sub, bod, email, ["admin@mail.net", ],
    )


'''
Проверка авторизации,
в дальнейшем у каждого пользователя будет своя "визитная карточка".
'''


@login_required
def user_contact(request):
    form = ContactForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            body = form.cleaned_data['body']
            send_msg(email, name, subject, body)
            form.save()
            return redirect('thank-you')
    return render(request, 'contact.html', {'form': form})


def thankyou(request):
    return render(request, 'thankyou.html')

templates/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Данная страница всецело посвящена автору данного проекта(то есть мне)
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Через тернии к звездам...

                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Сказали бы вы мне год назад, 
              что я буду сидеть вечерами и разбираться в документации Питона,
              осваивая его медленно, но верно. Я бы рассмеялся и сказал вам,
              что программирование - это вообще не мое, но вот он я.
              Пишу свой первый проект и радуюсь каждой маленькой победе над собой и над тренажером!
            </p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            {% block header %}
            <!--Переопределение наследников-->
            {% endblock %}

            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
      </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {% now 'Y' %}, все права защищены.</p>
</footer> 

templates/group.html
{% extends "base.html" %}
{% block title %}
  Записи сообщества {{group.title}} 
{% endblock %}
{% block header %}
  {{group}}
{% endblock %}


{%block content%}
  <h1>{{ group.title }}</h1>
  <h1> 
    Записи сообщества {{group.title}}
  </h1>
 <p>
   {{group.description|linebreaksbr}}
 </p>
  {% for post in page %}
  <h1>
    Автор:<a href = "{% url 'posts:profile' post.author.username %}" ><strong class="d-block text-gray-dark">{{post.author.username}}</strong></a>  
    Дата публикации: {{post.pub_date|date:"d M Y"}}  
  </h1>
  <p>
    {{post.text|linebreaksbr}}
  </p>
  <hr>
  {% endfor %}
  {% include "paginator.html" %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  {% for post in page %}
  <h3>
      Автор:<a href = "{% url 'posts:profile' post.author.username %}" ><strong class="d-block text-gray-dark">{{post.author.username}}</strong></a>
      Дата публикации: {{ post.pub_date|date:"d M Y" }} </br>
      {%if post.group != None %}
      Группа: <a href = "{% url 'posts:group' post.group.slug %}" >{{post.group}}</a>
      {% endif %}
      
  </h3>
  <p>
      {{ post.text|linebreaksbr }}
  </p>
  <a href = "{% url 'posts:post' post.author.username post.id %}" >Посмотреть</a>
  {% if not forloop.last %}
  <hr>
  {% endif %}
  {% endfor %}

  {% include "paginator.html" %}
  
{% endblock %} 

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: <a href = "{% url 'posts:profile' user.username %}" ><strong class="p-2 text-gray-dark">{{user.username}}</strong></a>
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

templates/new.html
{% extends "base.html" %}
{% block title %}
{% if not post %}Добавить запись {% else %} Редактировать запись {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if not post %} Добавить запись {% else %} Редактировать запись {% endif %}</div>
            <div class="card-body">

                {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                          {{ error|escape }}
                        </div>
                    {% endfor %}
                    <form method="post">
                    {% csrf_token %}
                  
                   
                    {% for field in form %}
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-6">

                                {# подключаем фильтр и указываем класс #}
                                {{ field|addclass:"form-control" }}
                                
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                    </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">              
                    <button type="submit" class="btn btn-primary">
                        {% if post %} Сохранить {% else %} Добавить {% endif %}
                    </button>
                </div>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

templates/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/post.html
{% extends "base.html" %}
{% block title %}
  Просмотр записи автора {{author.username}} 
{% endblock %}
{% block header %}
  {{author.username}}
{% endblock %}


{%block content%}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    <!-- Имя автора -->
                                    {{author.get_full_name}} 
                                </div>
                                <div class="h3 text-muted">
                                     <!-- username автора -->
                                     <a href = "{% url 'posts:profile' author.username %}" ><strong class="p-2 text-gray-dark">@{{author.username}}</strong></a>
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: XXX <br />
                                        Подписан: XXX
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            <!--Во view нет вызова всех постов без ограничительного фильтра-->    
                                            Записей:{{author.posts.count}}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

            <!-- Пост -->

                <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                                <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="{% url 'posts:post' author.username post.id %}"><strong class="d-block text-gray-dark">@{{author.username}}</strong></a>
                                        <h1>{%if post.group != None %}
                                                Группа: <a href = "{% url 'posts:group' post.group.slug %}" >{{post.group}}</a>
                                                {% endif %}
                                            </h1>
                                            {{post.text|linebreaksbr}}  
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                <!-- Ссылка на редактирование, показывается только автору записи -->
                                                {% if author == request.user %}
                                                <a class="btn btn-sm text-muted" href="{% url 'posts:post_edit' author.username post.id%}" role="button">Редактировать</a>
                                                {% endif %}
                                        </div>
                                        <!-- Дата публикации  -->
                                        <small class="text-muted">{{post.pub_date|date:"d M Y"}}</small>
                                </div>
                        </div>
                </div>
        </div>
     </div>
    </div>
</main>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}
  Записи автора {{author.username}} 
{% endblock %}
{% block header %}
  {{author.username}}
{% endblock %}


{%block content%}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        <!-- Имя автора -->
                                        {{author.get_full_name}}
                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                        <a href = "{% url 'posts:profile' author.username %}" ><strong class="p-2 text-gray-dark">@{{author.username}}</strong></a>
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: XXX <br />
                                            Подписан: XXX
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей:{{author.posts.count}}
                                            </div>
                                    </li>
                            </ul>
                    </div>
            </div>

            <div class="col-md-9">                

                <!-- Начало блока с отдельным постом --> 
                {%for post in page %}
                    <div class="card mb-3 mt-1 shadow-sm">
                            <div class="card-body">
                                    <p class="card-text">
                                            <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                            <a href = "{% url 'posts:profile' author.username %}" ><strong class="d-block text-gray-dark">@{{author.username}}</strong></a>
                                            <!-- Текст поста -->
                                            <h1>{%if post.group != None %}
                                                Группа: <a href = "{% url 'posts:group' post.group.slug %}" >{{post.group}}</a>
                                                {% endif %}
                                            </h1>
                                            {{post.text|linebreaksbr}} 
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group ">
                                                    <!-- Ссылка на страницу записи в атрибуте href-->
                                                    <a class="btn btn-sm text-muted" href = "{% url 'posts:post' author.username post.id %}" role="button">Добавить комментарий</a>
                                                    <!-- Ссылка на редактирование, показывается только автору записи -->
                                                    {% if post.author == request.user %}
                                                    <a class="btn btn-sm text-muted" href = "{% url 'posts:post_edit' author.username post.id %}" role="button">Редактировать</a>
                                                    {% endif %}
                                            </div>
                                            <!-- Дата публикации  -->
                                            <small class="text-muted">{{post.pub_date|date:"d M Y"}}</small>
                                    </div>
                            </div>
                    </div>
                <!-- Конец блока с отдельным постом --> 
                {% endfor %}

                <!-- Остальные посты -->  

            {% include "paginator.html" %}<!-- Здесь постраничная навигация паджинатора -->
     </div>
    </div>
</main>
{% endblock %}

templates/tech.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  О Технологиях
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст о текхнологиях
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Технологии развиваются быстро, о них будет написано подробно чуть позже</p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

users/templates/contact.html
{% extends "base.html" %}
{% block title %}Контакт{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Контакт</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                          {{ error|escape }}
                        </div>
                    {% endfor %}


                <form method="post" action="{% url 'contact' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}
                                    
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Готово
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                          {{ error|escape }}
                        </div>
                    {% endfor %}


                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}
                                    
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

users/templates/thankyou.html
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>

  <body>
  <div class="container">
    <h1>Спасибо</h1>
    <p class="lead">
      Обязательно отвечу на предложение в ближайшее время.
    </p>
  </div>

  </body>
</html>